config/routes.rb
Rails.application.routes.draw do

  devise_for :people, controllers: {
    sessions:      'people/sessions',
    passwords:     'people/passwords',
    registrations: 'people/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :person do
    post 'people/sign_up/confirm' => 'people/registrations#confirm'
    post 'people/sign_up/complete' => 'people/registrations#complete'
  end

  devise_scope :user do
    post 'users/sign_up/confirm' => 'users/registrations#confirm'
    post 'users/sign_up/complete' => 'users/registrations#complete'
  end

  root to: "home#index"
  get "people/complete" => "people#complete", as: "people/complete"
  get "users/complete" => "users#complete", as: "users/complete"

  # レッスンカテゴリーの検索用ページ
  get 'people/categories'

  resources :users, :only => [:index, :show]
  resources :people, :only => [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/large_category.rb
class LargeCategory < ApplicationRecord
  has_many :middle_categories
  accepts_nested_attributes_for :middle_categories, allow_destroy: true
end

app/models/middle_category.rb
class MiddleCategory < ApplicationRecord
  has_many :people_middle_categories, dependent: :destroy
  has_many :people, through: :people_middle_categories

  belongs_to :large_category
end

app/models/people_middle_category.rb
class PeopleMiddleCategory < ApplicationRecord
  belongs_to :person
  belongs_to :middle_category
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :personinfo, dependent: :destroy, inverse_of: :person

  has_many :people_middle_categories, dependent: :destroy
  has_many :middle_categories, through: :people_middle_categories

  accepts_nested_attributes_for :personinfo, update_only: true
end

app/models/personinfo.rb
class Personinfo < ApplicationRecord
	belongs_to :person, inverse_of: :personinfo, optional: true
	mount_uploader :image, ImageUploader

	# validates :firstname, presence: true
	# validates :lastname, presence: true
	# validates :sex, presence: true
	# validates :age, presence: true
	# validates :live, presence: true
	# validates :country, presence: true
	# validates :image, presence: true
	# validates :copy, presence: true, length: { maximum: 25 }
	# validates :program, presence: true, length: { maximum: 400 }
	# validates :place, presence: true, length: { maximum: 400 }
	# validates :method, presence: true, length: { maximum: 400 }
	# validates :message, presence: true, length: { maximum: 400 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :userinfo, dependent: :destroy, inverse_of: :user

  # before_create :build_userinfo
  accepts_nested_attributes_for :userinfo, update_only: true
end

app/models/userinfo.rb
class Userinfo < ApplicationRecord
  belongs_to :user, inverse_of: :userinfo, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # 未ログイン時、ログインページへリダイレクト
	# before_action :authenticate_user!
	# before_filter :authenticate_person!

  # CSRF保護をオンにする以下の1行を有効にします。
  protect_from_forgery with: :exception
  # ログイン済ユーザーのみにアクセスを許可する
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:userinfo_attributes => [:user_id, :nickname, :sex, :age, :live, :country]])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:userinfo_attributes => [:user_id, :nickname, :sex, :age, :live, :country]])
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      middle_category_ids: [],
      :personinfo_attributes => [:person_id, :firstname, :lastname, :sex, :age, :live, :country, :copy, :program, :place, :method, :message, :image, :image_cache]
    ])
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :personinfo_attributes => [:person_id, :firstname, :lastname, :sex, :age, :live, :country, :copy, :program, :place, :method, :message, :image, :image_cache],
      :middle_categories_attributes => [:person_id,  {middle_category_ids:[]}]
  ])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/people/sessions_controller.rb
# frozen_string_literal: true

class People::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/people/unlocks_controller.rb
# frozen_string_literal: true

class People::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  	# puts params[:comment]
  	@people = Person.all
  end

  def show
  	# IDに紐付いた「personinfo」の情報を取得
  	@person = Person.find(params[:id]).personinfo
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	# IDに紐付いた「userinfo」の情報を取得
  	@users = User.all
  end

  def show
  	# IDに紐付いた「userinfo」の情報を取得
  	@user = User.find(params[:id]).userinfo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>

  <meta name="description" content="説明文">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="manifest" href="site.webmanifest">
  <link rel="apple-touch-icon" href="icon.png">
  <!-- favicon.icoはルートディレクトに配置 -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
</head>

<body>
  <div class="l-container">
    <div class="c-overlay"></div>

    <%= render "shared/header" %>

    <main class="l-contents">
      <section class="l-contents__inner">
        <!-- <p class="notice"><%= notice %></p> -->
        <!-- <p class="alert"><%= alert %></p> -->
        <%= yield %>
      </section>
    </main>

    <footer class="l-footer--regist">
      <ul class="c-footer-link">
        <!-- {{ range $val := seq 16 }} -->
        <li class="c-footer-link__item">
          <a href="#">リンクテキスト</a>
        </li>
        <!-- {{ end }} -->
      </ul>
      <p class="l-footer__copyright">Copyright 2012-2018 © freee K.K.</p>
      <!-- <div class="p-overlay-btn">
        <div class="c-btn--regest">
          <a href="/user-profile-registration">会員登録</a>
        </div>
        <div class="c-btn--cta">
          <a href="/">レッスン申し込み</a>
        </div>
      </div> -->
    </footer>
  </div>

  <%= render "shared/js" %>

</body>
</html>

app/views/shared/_footer.html.erb
<footer>
      <p>テキスト</p>
</footer>


</div>


<!-- <script src="js/vendor/modernizr-3.5.0.min.js"></script> -->
       <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
       <!-- <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script> -->
       <!-- <script src="/js/navigation.js"></script> -->

       <!-- Google Analytics: UA-XXXXX-YをあなたのIDに変更 -->
       <script>
       	window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
       	ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
       </script>
       <script src="https://www.google-analytics.com/analytics.js" async defer></script>
   </body>
 </html>

app/views/shared/_header.html.erb
        <header class="l-header">
          <nav class="p-navigation">
            <p class="c-hamburger">
              <a href="#">
                <span></span>
                <span></span>
                <span></span>
              </a>
            </p>
            <div class="c-navigation">

              <!--ログアウト状態-->
              <div class="c-navigation__item--member-logout">
                <p class="c-btn--regest">
                  <%= link_to new_user_registration_path do %>
                  会員登録はこちら
                  <% end %>
                </p>
              </div>

              <ul class="c-navigation__item--list">
                <li><a href="/person"><i class="fas fa-users"></i>パーソンを探す</a></li>
                <li><a href="/lesson"><i class="fas fa-search"></i>レッスンを探す</a></li>
              </ul>

              <ul class="c-navigation__item--logout">
                <li>
                  <%= link_to new_user_session_path do %>
                  <i class="fas fa-sign-in-alt"></i>ログイン
                  <% end %>
                </li>
              </ul>

              <ul class="c-navigation__item--list">
                <li class="c-btn--cta">
                  <%= link_to new_person_registration_path do %>
                  <i class="far fa-play-circle"></i>先生になろう
                  <% end %>
                </li>
              </ul>
              <!--ログアウト状態-ここまで-->
              <br>
              <!--ログイン状態-->
              <div class="c-navigation__item--member-login">
                <div class="c-person-medium">
                  <%= link_to new_user_registration_path do %>
                  <div class="c-person-medium__item--thumbnail">
                    <img src="/img/bitmap.png">
                  </div>
                  <h3 class="c-person-medium__item--title">ニックネームニックネーム</h3>
                  <% end %>
                </div>
              </div>

              <ul class="c-navigation__item--list">
                <li><a href="/person"><i class="fas fa-users"></i>パーソンを探す</a></li>
                <li><a href="/lesson"><i class="fas fa-search"></i>レッスンを探す</a></li>
              </ul>

              <ul class="c-navigation__item--login">
                <li>
                  <%= link_to destroy_user_session_path , method: :delete do %>
                  <i class="fas fa-sign-in-alt"></i>ログアウト
                  <% end %>
                </li>
              </ul>

              <ul class="c-navigation__item--list">
                <li class="c-btn--cta">
                  <%= link_to new_person_registration_path do %>
                  <i class="far fa-play-circle"></i>先生になろう
                  <% end %>
                </li>
              </ul>
              <!--ログイン状態-ここまで-->
            </div>
          </nav>
          <h1 class="c-logo">
            <%= link_to root_path do %>
            <img src="https://c.stat100.ameba.jp/official/sp/img/logo.png" width="180">
            <% end %>
          </h1>

        </header>
        <!-- IE9未満への配慮が不要であれば、削除 -->

app/views/shared/_js.html.erb
<!-- <script src="js/vendor/modernizr-3.5.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>
<!-- <script src="/js/navigation.js"></script>
<script src="/js/accordion.js"></script>
<script src="/js/img-changePhoto.js"></script>
<script src="/js/overlay-btn.js"></script> -->

  <%= javascript_include_tag 'application' %>

<!-- Google Analytics: UA-XXXXX-YをあなたのIDに変更 -->
<script>
  window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
  ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>

<script>
  window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
  ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>